### ISSUE TITLE
Bowerbird not working on RhinoMAC?

### ISSUE THREAD

**Issue by zohozer** [oberbichler/Bowerbird#32]
I just installed the Bowerbird components on my RhinoMAC into my "/Users/user/Library/Application Support/McNeel/Rhinoceros/7.0/Plug-ins/Grasshopper (b45a29b1-4343-4035-989e-044e8580d9cf)/Libraries" but unfortunately when opening Grasshopper the Bowerbird components are not listed into the components tabs.

It is possible to make this components compatible with RhinoMAC?

P.S. I do tested using the latest RhinoMAC 7 WIP.

**Comment by oberbichler** [comment]
Hi, the latest version should also work on macOS.
