### ISSUE TITLE
Issue with BB Text Component

### ISSUE THREAD

**Issue by Pixelkar** [oberbichler/Bowerbird#4]
Hi ,

When you bake the BB Text Component . the Curve out out of "8" shows Issues while using it in Laser Cutter on anything. Even when you try to simplify the curve it shows error

Thanks

**Comment by oberbichler** [comment]
Sorry for the late reply! On my machine it the "8" looks correct and can be exploded/simplified without problems. Have you found a solution for your problem?

Greetings
