### ISSUE TITLE
RhinoCommon and Grasshopper Assembly versions

### ISSUE THREAD

**Issue by pm-Architect** [oberbichler/Bowerbird#76]
Hi @oberbichler 
Does Bowerbird have any specific dependencies on the 6.29.20238.11500 versions of the RhinoCommon or Grasshopper Assemblies?
If not, could you please roll it back to 6.12.*? Reason: The ShapeDiver Rhino 6 cloud systems will be able to work with anything under 6.17. Although we have Rhino 7 systems as well, this will also ensure wider compatibility for users still using older versions of Rhino.
Please let me know if this is possible, thanks.

**Comment by oberbichler** [comment]
Hi! There was no specific reason. I will check asap.

> will be able to work with anything under 6.17

<6.17 or <=6.17?

**Comment by pm-Architect** [comment]
6.12 would be ideal! Thanks :D

**Comment by oberbichler** [comment]
Seems to work. Do you have experience with old RhinoCommon versions? I guess that if I run it with a current Rhino version, the new version will be used.

**Comment by pm-Architect** [comment]
Rhino and Grasshopper allow running plugins built on older versions. So building against 6.12 means that anyone using Rhino from 6.12 to the latest release of 7 will be able to use the plugin.
I always build against older versions (as old as possible) to ensure widespread compatibility and hence a wider audience.
Unless you have any specific dependencies on the newer version, doing this won't have any effect on the plugin :)

**Comment by pm-Architect** [comment]
If you're wondering how to actually use an older version, the references are available as NuGet packages:
https://www.nuget.org/packages/RhinoCommon/6.12.19029.6381
https://www.nuget.org/packages/RhinoCommon/6.12.19029.6381
Check out the number of downloads for each version ;)

**Comment by oberbichler** [comment]
This is exactly [what I have done](https://github.com/oberbichler/Bowerbird/tree/feature/downgrade). I was just wondering what happens if people are using a newer version. I guess this works as long as McNeel does not delete any function.

**Comment by pm-Architect** [comment]
Exactly! They've got a pretty good track record in that regard ;D

**Comment by oberbichler** [comment]
merged with #79
