### ISSUE TITLE
Rhino 7 support? Documentation?

### ISSUE THREAD

**Issue by LyleSY** [oberbichler/Bowerbird#80]
Has this been updated to work with Rhino 7 and tested working? Is it possible to note that somewhere to make it clear to end users?

**Comment by oberbichler** [comment]
Hi! It works with Rhino 6 and 7 on Windows. There are some troubles with Rhino for Mac. At the moment there are only examples and no particular documentation. Which functions are you interested in?

**Comment by UnfoldAntwerp** [comment]
Hi Thomas @oberbichler, Which issues are you aware of on Mac? A quick test drive doesn't show any obvious issues to me but I haven't checked all components.

**Comment by oberbichler** [comment]
Hi,

There are no known problems and the plugin should work with macOS. However, I do not test the component with my Mac frequently.

Best
Thomas
